folio-org/folio-service-tools

PULL_REQUEST_TEMPLATE.md, folio-service-tools-dev/pom.xml, folio-service-tools-dev/src/main/java/org/folio/common/OkapiParams.java, folio-service-tools-dev/src/main/java/org/folio/common/pf/PartialFunction.java, folio-service-tools-dev/src/main/java/org/folio/config/ModConfiguration.java, folio-service-tools-dev/src/main/java/org/folio/db/DbUtils.java, folio-service-tools-test/pom.xml, pom.xml
Code-style whitespace scan. Assist initial editor config.
Prevent extraneous diffs, etc.
Find and remove trailing spaces.
There were no tabs.
https://dev.folio.org/guides/developer-setup/#use-editorconfig-for-consistent-whitespace
The remainder of this initial setup is fine. Thanks.
Also using this initial PR to configure some GitHub status checks.
=> FOLIO-722 initial repo setup

folio-service-tools-test/pom.xml, pom.xml
Tune up Jacoco coverage for Sonar
=> Tune up Jacoco coverage for Sonar

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
=> Making release 1.0.0

folio-service-tools-dev/pom.xml, folio-service-tools-dev/src/main/java/org/folio/rest/exc/ExceptionHandlers.java, folio-service-tools-dev/src/test/java/org/folio/rest/exc/ExceptionHandlersTest.java, folio-service-tools-test/pom.xml, pom.xml
Specify files to be excluded from sonar analysis. Add more tests
=> Another attempt to configure sonar coverage

folio-service-tools-dev/pom.xml, folio-service-tools-dev/src/main/java/org/folio/rest/exc/RestExceptionHandlers.java, folio-service-tools-dev/src/main/java/org/folio/service/exc/ServiceExceptions.java, folio-service-tools-dev/src/test/java/org/folio/rest/exc/RestExceptionHandlersTest.java, pom.xml
Minor class renaming for better readability.
=> Minor class renaming

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
Update RMB version. Rollback to 1.0.0 version of the lib
=> Version updates

folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
=> Release 1.0.0

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
=> Release 1.0.1

folio-service-tools-dev/pom.xml, folio-service-tools-dev/src/main/java/org/folio/db/CqlQuery.java, folio-service-tools-dev/src/main/java/org/folio/rest/ResponseHelper.java, folio-service-tools-dev/src/main/java/org/folio/rest/exc/ExceptionPredicates.java, folio-service-tools-dev/src/main/java/org/folio/rest/exc/RestExceptionHandlers.java, folio-service-tools-dev/src/main/java/org/folio/rest/exc/RestExceptionResponses.java, folio-service-tools-dev/src/main/java/org/folio/rest/validate/Validation.java, folio-service-tools-dev/src/main/java/org/folio/rest/validate/ValidationMethods.java, folio-service-tools-dev/src/test/java/org/folio/common/pf/TestData.java, folio-service-tools-dev/src/test/java/org/folio/rest/exc/RestExceptionHandlersTest.java, folio-service-tools-dev/src/test/java/org/folio/rest/validate/ValidationMethodsEnumTest.java, folio-service-tools-dev/src/test/java/org/folio/rest/validate/ValidationMethodsEqualsTest.java, folio-service-tools-dev/src/test/java/org/folio/rest/validate/ValidationTest.java
- refactor exception handler;
- introduce simple validation tool which can be composed as future
=> Modnotes 104 refactor notelinks on parts

folio-service-tools-dev/src/main/java/org/folio/db/exc/DbExcUtils.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/DbExcUtilsTest.java
Add utility methods to quickly identify constraint violation type from Throwable
=> Add utility methods to quickly identify constraint violation type from Throwable

folio-service-tools-dev/src/main/java/org/folio/db/exc/AuthorizationException.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/DbExcUtils.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/AuthorizationExceptionTranslation.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/PostgreSQLExceptionTranslator.java, folio-service-tools-dev/src/main/java/org/folio/rest/exc/RestExceptionHandlers.java, folio-service-tools-dev/src/main/java/org/folio/rest/exc/RestExceptionResponses.java, folio-service-tools-dev/src/test/java/org/folio/db/ErrorConstants.java, folio-service-tools-dev/src/test/java/org/folio/db/ErrorFactory.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/DbExcUtilsTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/AuthorizationExceptionTranslationTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/PostgreSQLExceptionTranslatorTest.java, folio-service-tools-dev/src/test/java/org/folio/rest/exc/RestExceptionHandlersTest.java
Add changes to support constraint violation exception analysis so that error message could be more user-friendly. Handle authorization / unprocessable entity exceptions  
- add utility methods to differentiate different types of constraint violation
- introduce AuthorizationException and translate DB invalid authorization exception into it
- add REST exception handlers to build a response in case of authorization issue / constraint violation / data exception
=> MODNOTES-100 Handle authorization / unprocessable entity exceptions

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
=> Release 1.1.0

folio-service-tools-dev/src/main/java/org/folio/db/exc/Constraint.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/ConstrainViolationTranslation.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/ConstraintTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/ConstrainViolationTranslationTest.java
Populate constraint columns for PK/Unique/FK from Detail part of postgres exception
=> MODNOTES-114 populate constraint columns from Detail

folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/AuthorizationExceptionTranslation.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/ConstrainViolationTranslation.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/DataExceptionTranslation.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/ErrorMessageAdapter.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/GenericDBExceptionTranslation.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/InformationMessageConstants.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/InvalidUUIDTranslation.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/PostgreSQLExceptionTranslator.java, folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/TranslationUtils.java, folio-service-tools-dev/src/main/java/org/folio/rest/exc/RestExceptionHandlers.java, folio-service-tools-dev/src/test/java/org/folio/db/ErrorBuilder.java, folio-service-tools-dev/src/test/java/org/folio/db/ErrorFactory.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/AuthorizationExceptionTranslationTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/ConstrainViolationTranslationTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/DataExceptionTranslationTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/ErrorMessageAdapterTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/GenericDBExceptionTranslationTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/InvalidUUIDTranslationTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/InvalidValueParserTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/PostgreSQLExceptionTranslatorTest.java, folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/TranslationUtilsTest.java, folio-service-tools-dev/src/test/java/org/folio/rest/exc/RestExceptionHandlersTest.java, folio-service-tools-test/src/main/java/org/folio/test/util/TestSetUpHelper.java, pom.xml
Update RMB to 29.0.1
Use classes from jasync-sql library instead of mauricio/postgresql-async
Add "moduleTo" attribute to POST /_/tenant during test setup
=> MODKBEKBJ-339: Update RMB to 29.0.1

folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
Remove explicit dependency to okapi-common, upgrade to RMB 29.1.1
=> Remove explicit dependency to okapi-common

folio-service-tools-dev/src/main/java/org/folio/service/exc/InvalidDataException.java, folio-service-tools-dev/src/main/java/org/folio/service/exc/InvalidFieldValueException.java, folio-service-tools-dev/src/main/java/org/folio/service/exc/ServiceExceptions.java
Introduce 2 types of invalid data exceptions:
- general one
- invalid field value
=> Introduce invalid data exceptions

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
=> Release 1.4.1

folio-service-tools-dev/src/main/java/org/folio/config/ModConfiguration.java, folio-service-tools-dev/src/main/java/org/folio/db/CqlQuery.java, folio-service-tools-dev/src/main/java/org/folio/db/DbUtils.java, folio-service-tools-dev/src/main/java/org/folio/rest/exc/RestExceptionResponses.java, folio-service-tools-dev/src/main/java/org/folio/rest/validate/Validation.java, folio-service-tools-dev/src/main/java/org/folio/util/FutureUtils.java, folio-service-tools-dev/src/main/java/org/folio/util/TokenUtils.java, folio-service-tools-dev/src/main/java/org/folio/util/UserInfo.java, folio-service-tools-dev/src/test/java/org/folio/db/DbUtilsTransactionTest.java, folio-service-tools-dev/src/test/java/org/folio/util/FutureUtilsTest.java, folio-service-tools-dev/src/test/java/org/folio/util/TokenUtilsTest.java, pom.xml
Move utility classes from mod-kb-ebsco-java:
- TokenUtils
- FutureUtils
Upgrade Vert.x version to 3.8.4
=> MODKBEKBJ-432 Move TokenUtils/FutureUtils from mod-kb-ebsco-java

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
=> Release 1.4.3

folio-service-tools-dev/src/main/java/org/folio/db/CqlQuery.java, folio-service-tools-dev/src/main/java/org/folio/db/RowSetUtils.java, folio-service-tools-dev/src/test/java/org/folio/db/DbUtilsTransactionTest.java, folio-service-tools-dev/src/test/java/org/folio/db/RowSetUtilsTest.java, folio-service-tools-test/src/main/java/org/folio/test/util/TokenTestUtil.java
=> MODCFIELDS-49 Add util classes

folio-service-tools-test/src/main/java/org/folio/test/util/TestSetUpHelper.java
This is to address issue described in [FOLIO-2605](https://issues.folio.org/browse/FOLIO-2605) when tests should be executed against a running PostgreSQL instance rather an embedded one. 
Initial approach was proposed in https://github.com/folio-org/folio-service-tools/pull/30. The main difference is that embedded instance will be started (if necessary) in `TestSetUpHelper.startVertxAndPostgres()` as it was before.
* call to `PostgresClient.getInstance(vertx)` to implicitly start embedded postgre or read the connection settings from env variables;
* do not force embedded instance to start: no longer call `startEmbeddedPostgres()`
=> FOLIO-2605: Use DB_ Postgres instance if available, otherwise start embedded pg

folio-service-tools-dev/src/main/java/org/folio/db/DbUtils.java, folio-service-tools-dev/src/test/java/org/folio/db/DbUtilsTest.java
Restore previously existed method to create DB params as JsonArray
=> Restore method to create DB params as JsonArray

folio-service-tools-dev/pom.xml, pom.xml
Update RMB/mod-configuration to stable versions
=> Update RMB/mod-configuration to stable versions

folio-service-tools-dev/src/main/java/org/folio/db/DbUtils.java, folio-service-tools-dev/src/main/java/org/folio/util/TokenUtils.java, folio-service-tools-dev/src/test/java/org/folio/db/DbUtilsTransactionTest.java, folio-service-tools-test/pom.xml, folio-service-tools-test/src/main/java/org/folio/test/util/TestSetUpHelper.java, pom.xml
Upgrade to RMB 33
https://issues.folio.org/browse/FST-12
=> FST-12 Upgrade to RMB 33

folio-service-tools-dev/src/main/java/org/folio/db/CqlQuery.java, folio-service-tools-dev/src/main/java/org/folio/db/RowSetUtils.java, folio-service-tools-dev/src/test/java/org/folio/db/DbUtilsTransactionTest.java, folio-service-tools-dev/src/test/java/org/folio/db/RowSetUtilsTest.java, folio-service-tools-dev/src/test/java/org/folio/rest/tools/utils/ModuleName.java, pom.xml
Upgrading notes:
https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-331
=> FST-15: Upgrade folio-service-tools to RMB 33.1.1 and Vert.x 4.1.4

folio-service-tools-dev/pom.xml
mod-configuration-client 5.7.1 is for Vert.x 4.1.4
=> FST-16: Upgrade folio-service-tools to mod-configuration-client 5.7.1

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
Release v1.10.0
[FST-31](https://issues.folio.org/browse/FST-31)
=> Tmp release v1.10

folio-service-tools-spring-dev/pom.xml, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/config/KafkaConfig.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioEnvironment.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaProperties.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaUtils.java, folio-service-tools-spring-dev/src/main/resources/META-INF/spring.factories, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioEnvironmentTest.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioKafkaPropertiesTest.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/KafkaAdminServiceTest.java, folio-service-tools-spring-dev/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, lombok.config, pom.xml
Add mechanism of Kafka topic creation
Create a new maven module
=> FST-32 Implement topic creation

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/config/KafkaConfig.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/config/condition/OnKafkaTopicsPropertyCondition.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/config/condition/OnKafkaTopicsPropertyConditionTest.java
Change the condition on KafkaConfig to not have Kafka related beans if there is no required property
=> FST-34 Change condition on KafkaConfig

folio-service-tools-spring-dev/README.md, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/batch/MessageBatchProcessor.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/config/RetryTemplateConfiguration.java, folio-service-tools-spring-dev/src/main/resources/META-INF/spring.factories, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/batch/MessageBatchProcessorTest.java
Add batch message processor with fallback
=> FST-35 Add batch message processor with fallback

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/SystemUserExecutionContextBuilder.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/SystemUserExecutionContextBuilderTest.java
Populate okapi headers in folio context
=> FST-34 Populate okapi headers in folio context

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/SystemUserExecutionContextBuilder.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/SystemUserExecutionContextBuilderTest.java
Not pull into headers null values
=> FST-34 Not pull into headers null values

folio-service-tools-spring-test/pom.xml, folio-service-tools-spring-test/src/main/java/org/folio/spring/test/extension/DatabaseCleanup.java, folio-service-tools-spring-test/src/main/java/org/folio/spring/test/extension/impl/DatabaseCleanupExtension.java
Add DatabaseCleanup extension for tests
=> FST-36 Add DatabaseCleanup extension for tests

folio-service-tools-dev/pom.xml, folio-service-tools-spring-dev/pom.xml, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/config/properties/FolioEnvironment.java, folio-service-tools-spring-dev/src/main/resources/META-INF/spring.factories, folio-service-tools-spring-dev/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioEnvironmentTest.java, folio-service-tools-spring-test/pom.xml, folio-service-tools-test/pom.xml, pom.xml
[FST-37](https://issues.folio.org/browse/FST-37)  | Update the library to Spring boot v3.0.0 and identify issues.
New version of artifact: 3.0.0
=> Migration Spring boot v3

folio-service-tools-dev/src/test/java/org/folio/db/RowSetUtilsTest.java, folio-service-tools-spring-dev/pom.xml, folio-service-tools-spring-test/pom.xml, pom.xml
For Orchid upgrade
* RMB from 35.0.0 to 35.0.5 and
* Vert.x from 4.3.3 to 4.3.7.
This provides several bug fixes.
https://issues.folio.org/browse/FST-40
=> FST-40: RMB 35.0.5, Vert.x 4.3.7

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/PrepareSystemUserService.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/PrepareSystemUserServiceTest.java
Use lastname property for lastname in system-user creation
=> FST-44 Use lastname property for lastname in system-user creation

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/SystemUserService.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/SystemUserServiceTest.java
Use additional context to get user id
=> FST-46 Use additional context to get user id

pom.xml
Support nested Folio Execution Contexts
[MSEARCH-531](https://issues.folio.org/browse/MSEARCH-531)
- Upgrade folio-spring-base
=> chore: Upgrade folio-spring-base

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaTopic.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioMessageProducer.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioMessageProducerTest.java
Extend message producer with key function
https://issues.folio.org/browse/FST-64
=> feat(kafka): extend message producer with key function

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/client/AuthnClient.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/client/PermissionsClient.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/client/UsersClient.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/config/SystemUserConfig.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/config/properties/FolioEnvironment.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/context/ExecutionContextBuilder.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaScopedExecutionService.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/PrepareSystemUserService.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/SystemUserScopedExecutionService.java, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/SystemUserService.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/KafkaScopedExecutionServiceTest.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/SystemUserScopedExecutionServiceTest.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/SystemUserServiceTest.java
_Resolve Conflicting same name beans existing in FST and folio-spring-support._
_Rename component names_
[_FST-62_](https://issues.folio.org/browse/FST-62)
=> FST-62: Refactor component names not to conflict with the ones from folio-spring-support

NEWS.md, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/config/KafkaConfig.java
Fix issue with visability of classes from different packages
Add one more value for basePackages parameter
=> FST-68 Add kafka config

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-dev/src/test/java/org/folio/config/ModConfigurationTest.java, folio-service-tools-spring-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
Prepare for next v4.1.0 development iteration
=> Prepare for next development iteration

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-spring-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
Prepare for 4.2.0 development iteration
=> Prepare for 4.2.0 development iteration

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaProperties.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioKafkaPropertiesTest.java
Fix data type for kafka maxPollIntervalMs
[FST-85](https://folio-org.atlassian.net/browse/FST-85)
[MSEARCH-873](https://folio-org.atlassian.net/browse/MSEARCH-873)
=> fix(kafka): Fix data type for kafka maxPollIntervalMs

NEWS.md, folio-service-tools-dev/pom.xml, folio-service-tools-spring-dev/pom.xml, folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaProperties.java, folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioKafkaPropertiesTest.java, folio-service-tools-test/pom.xml, pom.xml
Release v4.1.1, prepare for 4.1.2 development iteration
[FST-86](https://folio-org.atlassian.net/browse/FST-86)
=> Prepare for 4.1.2 development iteration

pom.xml
Upgrade folio-spring-base dependency version from 8.2.2 to 8.3.0-SNAPSHOT
=> fix(deps): Update folio-spring-base version

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioMessageProducer.java, pom.xml
Do not fail on javadoc generation
_How does this change fulfill the purpose? Provide a high-level overview of the technical approach taken to address the problem._
=> fix: do not fail on javadoc generation

NEWS.md, README.md, folio-service-tools-dev/pom.xml, folio-service-tools-spring-dev/pom.xml, folio-service-tools-test/pom.xml, pom.xml
Prepare for next development iteration 5.1.0
=> Prepare for next development iteration 5.1.0
