folio-service-tools-dev/src/main/java/org/folio/db/DbUtils.java
folio-service-tools-dev/src/main/java/org/folio/rest/exc/RestExceptionHandlers.java
folio-service-tools-dev/src/test/java/org/folio/rest/exc/RestExceptionHandlersTest.java
pom.xml

Update to use `RMB 25.0.1`. This is necessary for `mod-notes` to be updated to RMB 25.
Updated POM file and a few Java references due to package renaming.
None.
N/A.

Update to RMB25

---

folio-service-tools-dev/src/main/java/org/folio/db/exc/ConstraintViolationException.java
folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/ConstrainViolationTranslation.java
folio-service-tools-dev/src/main/java/org/folio/db/exc/translation/postgresql/InvalidValueParser.java
folio-service-tools-dev/src/test/java/org/folio/db/ErrorFactory.java
folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/ConstrainViolationTranslationTest.java
folio-service-tools-dev/src/test/java/org/folio/db/exc/translation/postgresql/InvalidValueParserTest.java

Per [MODNOTES-114](https://issues.folio.org/browse/MODNOTES-114), populate PK/FK/Unique exceptions with column details and invalid values
- modify ConstraintViolationException translation to parse invalid values from Detail message of postgres exception

MODNOTES-114  Populate PK/FK/Unique exceptions with column details and invalid values

---

folio-service-tools-dev/pom.xml
folio-service-tools-test/pom.xml
folio-service-tools-test/src/main/java/org/folio/test/util/DBTestUtil.java
folio-service-tools-test/src/main/java/org/folio/test/util/TestBase.java
folio-service-tools-test/src/main/java/org/folio/test/util/TestSetUpHelper.java
folio-service-tools-test/src/main/java/org/folio/test/util/TestUtil.java
pom.xml

Refactor common test set up to remove duplication between modules
Copy TestBase and TestSetUpHelper from mod-notes and mod-kb-ebsco-java
Generalize TestBase so that it can be used by any module that needs
to set up Vert.x + Wiremock + Postgres during tests.
Copy DBTestUtil from mod-notes
Generalize DBTestUtil
`@BeforeClass` and `@AfterClass` methods from base class and from inheriting class can interact in a confusing way, so when extending TestBase we need to look out for that. 
https://stackoverflow.com/questions/2132734/beforeclass-and-inheritance-order-of-execution

MODCFIELDS-6: Move TestBase to folio-service-tools

---

folio-service-tools-dev/src/main/java/org/folio/db/DbUtils.java
folio-service-tools-dev/src/main/java/org/folio/util/FutureUtils.java
folio-service-tools-dev/src/test/java/org/folio/db/DbUtilsTransactionTest.java
folio-service-tools-dev/src/test/java/org/folio/util/FutureUtilsTest.java

Make utility methods available for mod-custom-fields
Copy executeInTransaction method to DbUtils
Copy mapVertxFuture and mapCompletableFuture methods to FutureUtils

MODCFIELDS-27: Move utility methods from mod-kb-ebsco-java

---

folio-service-tools-dev/src/main/java/org/folio/util/TokenUtils.java
folio-service-tools-dev/src/test/java/org/folio/util/TokenUtilsTest.java

Сonvert headers to case insensitive in `TokenUtils.fetchUserInfo(Map<String, String> okapiHeaders)`
Use `CaseInsensitiveMap` to wrap original headers map

MODKBEKBJ-432 Сonvert headers to case insensitive in TokenUtils.fetchUserInfo()

---

NEWS.md
pom.xml

Fix log4j2 `RCE` vulnerability
- log4j version set to 2.16.0
[FST-17](https://issues.folio.org/browse/FST-17)
[CVE-2021-44228](https://github.com/advisories/GHSA-jfh8-c2jp-5v3q)
[CVE-2021-45046](https://github.com/advisories/GHSA-7rjr-3q55-vv33)
`mvn dependency:tree -Dincludes=org.apache.logging.log4j` can be used to check log4j versions used

FST-17 Kiwi R3 2021 - Log4j vulnerability verification and correction

---

folio-service-tools-dev/pom.xml
pom.xml

Update to the latest RMB 33.2.* release.
See details: https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md
[FST-19](https://issues.folio.org/browse/FST-19)

FST-19 Upgrade to RAML Module Builder 33.2.4

---

folio-service-tools-dev/pom.xml
folio-service-tools-test/pom.xml
pom.xml

Update from wiremock:2.27.2 to wiremock-jre8:2.32.0.
This fixes multiple security vulnerabilities: https://mvnrepository.com/artifact/com.github.tomakehurst/wiremock/2.27.2
Explanation of the difference between wiremock and wiremock-jre8: http://wiremock.org/docs/download-and-installation/

FST-21: wiremock-jre8:2.32.0 fixing security vulnerabilities

---

pom.xml

Update log4j-slf4j-impl from 2.16.0 to 2.17.1 by using log4j-bom.

FST-22: Update log4j-slf4j-impl from 2.16.0 to 2.17.1

---

folio-service-tools-dev/pom.xml
pom.xml

Upgrade RMB, Vert.x, mod-configuration-client and Wiremock to indirectly upgrade jackson-databind from 2.13.1 to 2.13.2.1 fixing Denial of Service (DoS) https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518
Upgrade log4j from 2.17.1 to 2.17.2 because maintainers recommend it: https://logging.apache.org/log4j/2.x/

FST-24: jackson-databind 2.13.2.1 Denial of Service (CVE-2020-36518)

---

folio-service-tools-dev/pom.xml
folio-service-tools-test/pom.xml
pom.xml

Upgrade Vert.x from 4.3.1 to 4.3.3 fixing SSL that was incorrectly disabled: https://github.com/vert-x3/wiki/wiki/4.3.2-Release-Notes#vertx-web
This upgrades these vert.x dependencies:
* Upgrade jetty-client, jetty-http, and jetty-proxy from 9.4.46.v20220331 to 9.4.48.v20220622 fixing Improper Input Validation vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-2047
Upgrade RMB from 34.0.0 to 34.0.2 matching the Vert.x version.
Upgrade wiremock from 2.33.2 to 2.34.0. This upgrades these wiremock dependencies:
* Upgrade http2-server from 9.4.46.v20220331 to 9.4.48.v20220622 fixing an Insufficient Resource Pool vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-2048
* Upgrade commons-codec from 1.11 to 1.13 fixing an Information Exposure vulnerability: …

FST-29: Vertx 4.3.3, RMB 34.0.2, Wiremock 2.34.0 fixing vulns

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/PrepareSystemUserService.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/PrepareSystemUserServiceTest.java

_Avoid NPE while creating system user._
**Added null check on the place where getting first result from fetched users list**
[https://issues.folio.org/browse/FST-42](https://issues.folio.org/browse/FST-42)

FST-42: Added null check on System user creation

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/model/SystemUser.java
folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/PrepareSystemUserService.java
folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/SystemUserExecutionContextBuilder.java
folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/systemuser/SystemUserService.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/SystemUserExecutionContextBuilderTest.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/systemuser/SystemUserServiceTest.java

FolioExecutionContext is used to store the context of HTTP or Kafka messaging interactions. It contains several parameters needed for modules to interact with each other: tenant, token, okapi url, user id. For now context that is created for interaction on the base of the system user doesn't contain the user id that may be required for some interactions.
Do a call to /users to get id of the system-user ant put it into context

FST-46 Add userId to FolioExecutionContext for system-user

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/KafkaAdminServiceTest.java

Add kafka topic deletion by tenant id logic
Added kafka topic deletion by tenant id method
[FST-59](https://issues.folio.org/browse/FST-59)

FST-59: Added delete kafka topic method

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/KafkaAdminServiceTest.java

Fix "bean of type 'org.apache.kafka.clients.admin.KafkaAdminClient' that could not be found" error in dependant modules
- Add Kafka client creation on every call do "deleteTopics"
Kafka client creation added on every call to follow KafkaAdmin strategy, which also creates AdminClient every time it's needed

FST-59 Add Kafka client creation

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/KafkaAdminServiceTest.java

Improve kafka topic deletion by tenant id
Added completion logic for kafka topic deletion.
[FST-60](https://issues.folio.org/browse/FST-60)

FST-60: Improved kafka topic deletion by tenant id

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaProperties.java
folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaTopic.java
folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaUtils.java
folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/TenantIdCheckInterceptor.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/KafkaUtilsTest.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/TenantIdCheckInterceptorTest.java

Ensure that tenant identifier is included in every message produced to Kafka.
Add the ability to produce messages to tenant collection topics. All messages for an event type is sent to one topic instead of multiple. This is configurable through an environment variable.

add tenant identifying header & add tenant collection topics

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaUtils.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/KafkaUtilsTest.java

Allow spring modules that already have namespaces in their topic names to use KafkaUtils. This will bring tenant collection topics to the module
Add another method to create a tenant topic name with a namespace
https://issues.folio.org/browse/FST-66

FST-66 allow kafka topic names with namespace

---

NEWS.md
folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/KafkaAdminService.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/KafkaAdminServiceTest.java

Do not delete kafka topics if collection topic is enabled
If collection topics feature is enabled then do nothing
https://folio-org.atlassian.net/browse/FST-77

fix(kafka): do not delete kafka topics if collection topic is enabled

---

.github/workflows/postgres.yml
NEWS.md
folio-service-tools-dev/pom.xml
folio-service-tools-dev/src/test/java/org/folio/rest/tools/utils/ModuleName.java
folio-service-tools-test/pom.xml
pom.xml

https://folio-org.atlassian.net/browse/FST-82
For Ramsons:
Upgrade RMB from 35.2.2 to Ramsons version 35.3.0.
Upgrade folio-spring-support/folio-spring-base from 8.2.0-SNAPSHOT to Ramsons final version 8.2.0.
Upgrade dependencies for Ramsons.
Change version in pom.xml
Add .github/workflows/postgres.yml, see https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-353
Bump log4j-slf4j-impl to log4j-slf4j2-impl for testcontainers logging.
Add getModuleVersion() to ModuleName.java, otherwise mock(PostgresClient.class) fails.

FST-82: Ramsons dependencies: RMB 35.3.0, folio-spring-support 8.2.0

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaProperties.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioKafkaPropertiesTest.java

Add `maxPollRecords` and `maxPollIntervalMs` to `KafkaListenerProperties`
[FST-85](https://folio-org.atlassian.net/browse/FST-85)
[MSEARCH-873](https://folio-org.atlassian.net/browse/MSEARCH-873)

feat(kafka): Add `maxPollRecords` and `maxPollIntervalMs` to `KafkaListenerProperties`

---

folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaProperties.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioKafkaPropertiesTest.java

Add `autoOffsetReset` to `KafkaListenerProperties`
[FST-87](https://folio-org.atlassian.net/browse/FST-87)
[MODELINKS-298](https://folio-org.atlassian.net/browse/MODELINKS-298)

feat(kafka): Add `autoOffsetReset` to `KafkaListenerProperties`

---

NEWS.md
folio-service-tools-spring-dev/src/main/java/org/folio/spring/tools/kafka/FolioKafkaProperties.java
folio-service-tools-spring-dev/src/test/java/org/folio/spring/tools/kafka/FolioKafkaPropertiesTest.java

Introduce a new configuration property sharedGroup that will determine whether the groupId should be shared across all module instances or made unique per instance.
https://folio-org.atlassian.net/browse/FST-95

feat(kafka): introduce sharedGroup property to control Kafka consumer group behavior
